# Test Samplers by Hopping on a Graph

Let's test samplers by checking whether they run a model the same way. The model is that a particle hops around a graph, from graph node to graph node. Each hop is determined by a continuous univariate distribution. We'll let a particle hop around and then ask, at the end, how much time it spent on each node.

In [1]:
using Pkg
Pkg.activate(".")
using Fleck
using LinearAlgebra
using Revise

  Activating project at `~/dev/Fleck/examples`


In [6]:
include("../test/graph_occupancy.jl")

sample_run_graph_occupancy (generic function with 2 methods)

Make the model. This model is made by a random number generator, where the random number generator determines which nodes are connected (so you can hop from one to the other) and which distribution determines the speed of each hop.

Our plan is to use bootstrapping to estimate how much variance we should expect with different samplers. We'll start with a sampler we trust and run this 100 times. Then assume the average result is our expected value. We look at the odds ratio of those 100 draws to see how big they can get. Then, when we want to test another sampler, run it 10 or 100 times and look to see if its odds ratios are mostly within the range that we've seen already.

In [3]:
Threads.nthreads()

24

In [12]:
model_rng = Xoshiro(3498217)  # Random number generator.
features = Dict{String,Bool}(
    "weibull"=>false, "gamma"=>false, "past"=>false, "future"=>false,
    "memory"=>false)
singleton_groc = GraphOccupancy(features, model_rng)
length(singleton_groc)

8

In [13]:
function generate_samples(singleton_groc, singleton_sampler, trial_cnt)
    occupancy = zeros(Float64, (length(singleton_groc), trial_cnt))
    rng = Xoshiro(24370233)
    Threads.@threads for trial_idx in 1:trial_cnt
        groc = deepcopy(singleton_groc)
        sampler = deepcopy(singleton_sampler)
        occ, observations = run_graph_occupancy(groc, 1e6, sampler, rng)
        occupancy[:, trial_idx] .= occ
    end
    occupancy
end

generate_samples (generic function with 1 method)

In [24]:
# sampler = FirstReaction{keyspace(GraphOccupancy)}()
sampler = FirstToFire{keyspace(GraphOccupancy)}()
trial_cnt = 100
occupancy = generate_samples(singleton_groc, sampler, trial_cnt)

Expected old time 543522.0753771221 to be less than new time 543522.0753771221
Transition was Exponential{Float64}(θ=1.1014994474646027)
Transition shift 0.0
Transition memory false
Transition consumed 0.0


Expected old time 42304.429854061214 to be less than new time 42304.429854061214
Transition was Exponential{Float64}(θ=0.8604693692995262)
Transition shift 0.0
Transition memory false
Transition consumed 0.0
Expected old time 24794.073455339607 to be less than new time 24794.073455339607
Expected old time 995852.6007875177 to be less than new time 995852.6007875177
Transition was Exponential{Float64}(θ=0.8267125360131644)
Transition shift 0.0
Transition memory false
Transition consumed 0.0
Transition was Exponential{Float64}(θ=0.8176999194582568)
Transition shift 0.0
Transition memory false
Transition consumed 0.0


Expected old time 237566.0311051297 to be less than new time 237566.0311051297
Transition was Exponential{Float64}(θ=0.8267125360131644)
Transition shift 0.0
Transition memory false
Transition consumed 0.0


Expected old time 474444.79262231395 to be less than new time 474444.79262231395
Expected old time 466293.1951599712 to be less than new time 466293.1951599712
Expected old time 463400.4453006308 to be less than new time 463400.4453006308
Expected old time 486937.5848358796 to be less than new time 486937.5848358796
Transition was Exponential{Float64}(θ=1.0981100851036945)
Transition was Exponential{Float64}(θ=0.8267125360131644)
Transition shift 0.0
Transition memory false
Transition consumed 0.0
Transition shift 0.0
Transition memory false
Transition consumed 0.0
Transition was Exponential{Float64}(θ=0.8382691578948054)
Transition was Exponential{Float64}(θ=0.987968159117249)
Transition shift 0.0
Transition memory false
Transition consumed 0.0
Transition shift 0.0
Transition memory false
Transition consumed 0.0


Expected old time 829441.5278249845 to be less than new time 829441.5278249845
Expected old time 820752.1224604124 to be less than new time 820752.1224604124
Transition was Exponential{Float64}(θ=0.987968159117249)
Transition was Exponential{Float64}(θ=1.1676626805880466)
Transition shift 0.0
Transition memory false
Transition consumed 0.0
Transition shift 0.0
Transition memory false
Transition consumed 0.0


Expected old time 872323.4890605028 to be less than new time 872323.4890605028
Transition was Exponential{Float64}(θ=1.0707849892378047)
Transition shift 0.0
Transition memory false
Transition consumed 0.0


8×100 Matrix{Float64}:
 1.67543e5  1.67375e5       1.6738e5   …  1.67838e5       1.67467e5
 1.40328e5  1.41539e5  141072.0           1.40541e5       1.40942e5
 0.0        0.0             0.0           0.0             0.0
 1.54101e5  1.53452e5       1.54616e5     1.53719e5       1.52917e5
 1.33202e5  1.33262e5       1.33179e5     1.33107e5       1.33225e5
 1.46438e5  1.46237e5       1.45858e5  …  1.46332e5  146605.0
 1.21568e5  1.21234e5       1.20964e5     1.2187e5        1.21653e5
 1.3682e5   1.36899e5       1.36932e5     1.36592e5       1.37189e5

That zero dwell time is pesky. It means there was a component of the graph that wasn't connected, which is fine, but it will throw off the stats. We're going to see how likely each draw is using https://en.wikipedia.org/wiki/Multinomial_test.

In [25]:
function occupancy_likelihood_ratio(occupancy, mle)
    # Sometimes a graph node is disconnected, so remove those.
    keep_row = [sum(occupancy[check_idx,:]) > 0 for check_idx in 1:size(occupancy, 1)]
    occupancy = occupancy[keep_row, :]
    category_cnt = size(occupancy, 1)
    trial_cnt = size(occupancy, 2)
    odds_ratio = zeros(Float64, trial_cnt)
    for trial_idx in 1:trial_cnt
        relative_occupancy = occupancy[:, trial_idx] / sum(occupancy[:, trial_idx])
        log_odds = 0.0
        for node_idx in 1:category_cnt
            log_odds += occupancy[node_idx, trial_idx] * log(mle[node_idx] / relative_occupancy[node_idx])
        end
        odds_ratio[trial_idx] = -2 * log_odds
    end
    return odds_ratio
end

function maximum_likelihood(occupancy)
    # Sometimes a graph node is disconnected, so remove those.
    keep_row = [sum(occupancy[check_idx,:]) > 0 for check_idx in 1:size(occupancy, 1)]
    occupancy = occupancy[keep_row, :]
    category_cnt = size(occupancy, 1)
    trial_cnt = size(occupancy, 2)
    expected_occupancy = sum(occupancy; dims=2) / trial_cnt
    mle = expected_occupancy / sum(expected_occupancy)
end

maximum_likelihood (generic function with 1 method)

This set of 100 numbers is 100 odds ratios. If we do a bunch of draws from another sampler, we expect their odds ratios to be mostly in this range.

In [26]:
mle = maximum_likelihood(occupancy)
odds_ratios = occupancy_likelihood_ratio(occupancy, mle)
sort!(odds_ratios)

100-element Vector{Float64}:
  0.6959259206312609
  0.7389888001557381
  0.9118388052577302
  1.0274340622634668
  1.1540781389772405
  1.1960758574530246
  1.2188913988461536
  1.27211122585366
  1.3037830570398228
  1.3278271862999134
  ⋮
  9.659427084982426
  9.828239994666433
  9.844516415448112
 10.090493996332725
 10.696826313528987
 11.105238134560835
 11.498227040181064
 12.274181099861153
 14.251333072166972

Just checking that a perfect odds ratio is basically zero.

In [27]:
perfect = zeros(length(mle), 2)
perfect[:,1] .= mle * 1e6
perfect[:,2] .= mle * 1e6
occupancy_likelihood_ratio(perfect, mle)

2-element Vector{Float64}:
 -0.0
 -0.0

Now we're ready to evaluate the FirstToFire sampler. This should behave identically to the FirstReaction sampler, especially considering that this model disables all enabled nodes at every step.

In [28]:
# sampler = FirstToFire{keyspace(GraphOccupancy)}()
sampler = DirectCall{keyspace(GraphOccupancy)}()
trial_cnt = 10
first_to_fire = generate_samples(singleton_groc, sampler, trial_cnt)

8×10 Matrix{Float64}:
 1.67329e5  1.6704e5        1.66742e5  …  1.67188e5  1.667e5    1.66969e5
 1.40704e5  1.40758e5       1.41133e5     1.40871e5  1.40742e5  1.41089e5
 0.0        0.0             0.0           0.0        0.0        0.0
 1.54316e5  1.53145e5       1.54351e5     1.5375e5   1.53358e5  1.54091e5
 1.33224e5  1.33248e5       1.33124e5     1.33409e5  1.33422e5  1.3318e5
 1.46032e5  1.46732e5  146119.0        …  1.46198e5  1.46408e5  1.46136e5
 1.21521e5  1.21318e5       1.21515e5     1.21503e5  1.21625e5  1.21463e5
 1.36874e5  1.3776e5   137016.0           1.3708e5   1.37745e5  1.37072e5

Well, these odds don't look like they are in the right range.

In [29]:
ftf_odds_ratio = occupancy_likelihood_ratio(first_to_fire, mle)
sort!(ftf_odds_ratio)

10-element Vector{Float64}:
  0.8301085450626147
  2.4095056472231136
  2.835795004965348
  3.301451553912596
  4.432470953490565
  5.6542656918676215
  7.436824871371073
  7.645779158271125
 12.227999885770998
 13.75889926430844

Let's look in more depth at a single run with this sampler. We were using the total duration spent on each node during $10^6$ time units in order to evaluate if the sampler is working well. We can dig in by looking at another output of the model. The "observations" are a dictionary with an entry for each transition that tells us the total number of times that transition fired. If we group them by source node, that tells us how the particle left each node. If one type of transition wasn't firing properly due to some code error, it should show up as a bias in how the particle leaves the node.

In [20]:
rng = Xoshiro(2431243)
groc_ftf = deepcopy(singleton_groc)
sampler_ftf = FirstToFire{keyspace(GraphOccupancy)}()
occupancy_ftf, observations_ftf = run_graph_occupancy(groc_ftf, 1e7, sampler_ftf, rng)
groc_fr = deepcopy(singleton_groc)
sampler_fr = FirstReaction{keyspace(GraphOccupancy)}()
occupancy_fr, observations_fr = run_graph_occupancy(groc_fr, 1e7, sampler_fr, rng)


([1.6738282935241733e6, 1.4089668259955775e6, 0.0, 1.5388131323869396e6, 1.3337953835324484e6, 1.4636651028015716e6, 1.2127944262154773e6, 1.3681365085764797e6], Dict{Tuple{Int64, Int64}, TransitionObserver}((6, 8) => TransitionObserver(1.1641532182693481e-7, 3.2476032581180334, 0.20320362623926674, 296305.83808056405, 1458172), (4, 5) => TransitionObserver(6.079790182411671e-7, 15.794118637219071, 0.953892174398702, 1.5388131323869396e6, 1613194), (2, 5) => TransitionObserver(2.4226028472185135e-7, 5.105993431061506, 0.3392068351325051, 434479.18050250155, 1280868), (6, 2) => TransitionObserver(2.5425106287002563e-7, 3.17901730153244, 0.20326063683637335, 263497.33308410627, 1296352), (2, 6) => TransitionObserver(1.8905848264694214e-7, 4.58602390717715, 0.33980419658091715, 454470.44310875447, 1337448), (7, 8) => TransitionObserver(4.870817065238953e-7, 3.394221554888645, 0.23590552460236877, 289494.7671931413, 1227164), (7, 2) => TransitionObserver(1.1175870895385742e-8, 3.3584926370

Just looking at the raw occupancies shows that the total dwell time on node 4 could be off. Because this is a particle on a graph, you can see dwell time increase on one node because of a problem on a neighboring node that dumps out to it. That is, this high dwell time doesn't mean there is a problem with the distributions on that node. We'll have to dig a little deeper.

In [21]:
hcat(occupancy_fr, occupancy_ftf)

8×2 Matrix{Float64}:
 1.67383e6  1.67382e6
 1.40897e6  1.40847e6
 0.0        0.0
 1.53881e6  1.53621e6
 1.3338e6   1.33378e6
 1.46367e6  1.46421e6
 1.21279e6  1.21452e6
 1.36814e6  1.36899e6

In [24]:
sort(collect(observations_fr), by = a -> a[1][1])

24-element Vector{Pair{Tuple{Int64, Int64}, TransitionObserver}}:
 (1, 5) => TransitionObserver(0.0004142913967370987, 3.3154873268213123, 0.7184295751620818, 1.4606794013182377e6, 2033156)
 (1, 6) => TransitionObserver(0.21658028103411198, 3.0526506998576224, 0.5954087985870061, 851125.5648129521, 1429481)
 (2, 5) => TransitionObserver(7.729977369308472e-8, 6.9354165319819, 0.604621289751055, 1.0491019800773559e6, 1735139)
 (2, 6) => TransitionObserver(0.0009621046483516693, 6.907002249732614, 0.9138334472473781, 459827.28315317194, 503185)
 (2, 7) => TransitionObserver(0.00010904204100370407, 6.290487241465598, 0.915152276093912, 86389.4597109892, 94399)
 (4, 5) => TransitionObserver(5.442136898636818e-5, 8.550146629102528, 1.002282063517336, 14263.47604591521, 14231)
 (5, 6) => TransitionObserver(1.2330710887908936e-6, 3.0050602620467544, 0.31383245505469204, 56596.85877701821, 180341)
 (5, 1) => TransitionObserver(2.598389983177185e-7, 3.1215849025174975, 0.30532290833075487, 51152

In [25]:
sort(collect(observations_ftf), by = a -> a[1][1])

24-element Vector{Pair{Tuple{Int64, Int64}, TransitionObserver}}:
 (1, 5) => TransitionObserver(0.00013344455510377884, 3.4860272853984497, 0.7192650482879202, 1.4610955989357773e6, 2031373)
 (1, 6) => TransitionObserver(0.2165798507630825, 3.255967485718429, 0.5957999838047995, 851861.1134444748, 1429777)
 (2, 5) => TransitionObserver(3.5390257835388184e-8, 7.179546479135752, 0.6044925132029497, 1.048277064815816e6, 1734144)
 (2, 6) => TransitionObserver(0.0012898272834718227, 6.761778498068452, 0.9128762516626613, 459243.39455269, 503073)
 (2, 7) => TransitionObserver(8.825212717056274e-6, 6.503641169518232, 0.9122680860444093, 86056.98536082727, 94333)
 (4, 5) => TransitionObserver(0.00040536653250455856, 9.742169450037181, 1.0106061327827656, 14070.669186734445, 13923)
 (5, 6) => TransitionObserver(1.3532117009162903e-6, 3.060934967827052, 0.31297677441042165, 56536.12452949857, 180640)
 (5, 1) => TransitionObserver(4.807952791452408e-8, 3.2856816863641143, 0.30567179978108466, 511

Here, I'm trying to summarize, node-by-node, the probability of leaving that node for a neighbor. So, given that you are at node 5, you can go to nodes 4, 6, 7, 2, 8, or 1. Let's take every transitition from 5 to each of those, normalize by the each direction, and turn it into a probability for P[4|5], P[6|5], and so on. Do this for both the FirstReaction and FirstToFire and compare the tuples.

In [26]:
ways_out = Array{Dict{Int,Tuple{Float64,Float64}},1}()
node_cnt = nv(singleton_groc.g)
for init_ways in 1:node_cnt
    comparator = Dict{Int,Tuple{Float64,Float64}}()
    totals = zeros(Int64, 0)
    for obs in [observations_fr, observations_ftf]
        total_calls = 0
        for jump_to in neighbors(singleton_groc.g, init_ways)
            total_calls += obs[(init_ways, jump_to)].call_cnt
        end
        push!(totals, total_calls)
    end
    for way_out in neighbors(singleton_groc.g, init_ways)
        comparator[way_out] = (observations_fr[(init_ways, way_out)].call_cnt / totals[1],
            observations_ftf[(init_ways, way_out)].call_cnt / totals[2])
    end
    push!(ways_out, comparator)
end
ways_out

8-element Vector{Dict{Int64, Tuple{Float64, Float64}}}:
 Dict(5 => (0.5871698361682152, 0.5869069528913801), 6 => (0.41283016383178484, 0.41309304710862))
 Dict(5 => (0.7438255635152566, 0.7437730265274174), 6 => (0.21570713710972114, 0.2157676223971178), 7 => (0.04046729937502224, 0.04045935107546482))
 Dict()
 Dict(5 => (1.0, 1.0))
 Dict(4 => (0.0026944603856007402, 0.0026372674704053245), 6 => (0.034145294104393445, 0.03421647603634402), 7 => (0.25375186236989444, 0.2538830699664806), 2 => (0.3579985674733134, 0.3581423620582013), 8 => (0.03420133797159447, 0.03416097654853042), 1 => (0.31720847769520355, 0.3169598479200383))
 Dict(5 => (0.07502530896485297, 0.07480054028702526), 7 => (0.00020199782363635179, 0.00018191282820229535), 2 => (0.1308362413714053, 0.13054141583287485), 8 => (0.2645733136587848, 0.26479160167134635), 1 => (0.5293631381813206, 0.5296845293805512))
 Dict(5 => (0.3212420982211688, 0.3215274283660601), 6 => (0.33266913530563125, 0.33224327768157613), 2 => (6.

Actually, that node 4 only has a single path to another node. Let's see what the transition away is. It does have a relative_enabling_time, meaning it always claims to have a te 0.9 time units in the past.

In [27]:
singleton_groc.transition[(4,5)]

Transition(Exponential{Float64}(θ=1.0025218240393494), -0.9162202776014298, false, 0.0)

And in the other direction there is also an offset, this time into the future. This one is more suspicious, actually.

In [28]:
singleton_groc.transition[(5,4)] 

Transition(Gamma{Float64}(α=2.0, θ=2.0), 0.5815720074869544, false, 0.0)

In [34]:
for dest in [1,2,4,6,7,8]
    print("fr  ")
    println(observations_fr[(5,dest)])
    print("ftf ")
    println(observations_ftf[(5,dest)])
end

fr  TransitionObserver(2.598389983177185e-7, 3.1215849025174975, 0.30532290833075487, 511526.0930239218, 1675361)
ftf TransitionObserver(4.807952791452408e-8, 3.2856816863641143, 0.30567179978108466, 511491.3210866813, 1673335)
fr  TransitionObserver(1.1082738637924194e-7, 3.160241512581706, 0.30479267458294546, 576301.0747234095, 1890797)
ftf TransitionObserver(2.468004822731018e-8, 3.275742782279849, 0.30533464030926066, 577311.7764993749, 1890751)
fr  TransitionObserver(0.5849626380950212, 3.1341096609830856, 1.0365169941186374, 14750.67334330233, 14231)
ftf TransitionObserver(0.582367455586791, 3.1338147297501564, 1.03975434225738, 14476.499707249503, 13923)
fr  TransitionObserver(1.2330710887908936e-6, 3.0050602620467544, 0.31383245505469204, 56596.85877701821, 180341)
ftf TransitionObserver(1.3532117009162903e-6, 3.060934967827052, 0.31297677441042165, 56536.12452949857, 180640)
fr  TransitionObserver(3.3010728657245636e-5, 3.4024405404925346, 0.4397761422131869, 589392.383555535

In [30]:
observations_ftf[(5,4)]

TransitionObserver(0.582367455586791, 3.1338147297501564, 1.03975434225738, 14476.499707249503, 13923)